### ISSUE TITLE
npm install on osx fails at test # Test MelodyConverterWithPolyphonicInput with an undefined error

### ISSUE THREAD

**Issue by oveddan** [tensorflow/magenta-js#167]
I'm trying to install the packages for the demos.  In the `/music/demos folder I run:

    npm install

then this error shows up:

ok 73 should be equivalent
# Test MelodyConverterWithPolyphonicInput

/Users/danoved/Source/opensource/magenta-js/music/src/protobuf/proto.js:295
                        $root.tensorflow.magenta.NoteSequence.Note.encode(message.notes[i], writer.uint32(/* id 8, wireType 2 =*/66).fork()).ldelim();
                                                 ^
TypeError: Cannot read property 'NoteSequence' of undefined
    at Function.encode (/Users/danoved/Source/opensource/magenta-js/music/src/protobuf/proto.js:295:50)
    at Object.clone (/Users/danoved/Source/opensource/magenta-js/music/src/core/sequences.ts:81:43)
    at Test.<anonymous> (/Users/danoved/Source/opensource/magenta-js/music/src/core/data_test.ts:170:31)
    at Test.bound [as _cb] (/Users/danoved/Source/opensource/magenta-js/music/node_modules/tape/lib/test.js:76:32)
    at Test.run (/Users/danoved/Source/opensource/magenta-js/music/node_modules/tape/lib/test.js:95:10)
    at Test.bound [as run] (/Users/danoved/Source/opensource/magenta-js/music/node_modules/tape/lib/test.js:76:32)
    at Immediate.next (/Users/danoved/Source/opensource/magenta-js/music/node_modules/tape/lib/results.js:71:15)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)

**Comment by adarob** [comment]
The deps needs to be installed at the base `music` directory. You can go to `music` directory and run `yarn run-demos`. This will also install the deps.

**Comment by adarob** [comment]
Good call! Do you want to add that? If not, please file a new issue and
I'll do it next week.
