### ISSUE TITLE
Having trouble getting the node example working. 

### ISSUE THREAD

**Issue by classam** [tensorflow/magenta-js#351]
I've made a few small changes to the node example to get it working: 

```
const mv = require('@magenta/music/node/music_vae');

// These hacks below are needed because the library uses performance and fetch which
// exist in browsers but not in node. We are working on simplifying this!
global.performance = Date;
global.fetch = require('node-fetch');

// Your code:
const model = new mv.MusicVAE('https://storage.googleapis.com/magentadata/js/checkpoints/music_vae/mel_chords');

module.exports = () => {
    model
    .initialize()
    .then(() => model.sample(1))
    .then(samples => {
        console.warn(samples);
    });
};
```

When I try to run this, though, I get the following error: 
```
============================
Hi there �. Looks like you are running TensorFlow.js in Node.js. To
 speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================

%c MusicVAE  background:magenta; color:white Initialized model in 17.3s
(node:5348) UnhandledPromiseRejectionWarning: Error: Chord progression expected but not provided.
    at T.sample (/home/vagrant/server/node_modules/@magenta/music/node/music_vae.js:1:120380)
    at model.initialize.then (/home/vagrant/server/experiment_1.js:14:23)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Or, to get to the juicy bits: 

`(node:5348) UnhandledPromiseRejectionWarning: Error: Chord progression expected but not provided.`

... should I be providing a chord progression to something? I tried shouting the words "chord progression" at the sky to no avail.

**Comment by HarounAns** [comment]
I think it has something to do with that specific checkpoint. Try a different one.

**Comment by classam** [comment]
ayrp, that totally worked

**Comment by notwaldorf** [comment]
Great, glad it’s sorted!
